name: NeteaseMusic
on:
  push:
  workflow_dispatch:
    branches:
      - main
  schedule: 
    - cron: "0 0 * * *"

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: npm install
      - name: index.js
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_ID: 1443617119
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          REPO: "netease-music-card"
          AUTHOR: "nicetoday1344"
